model:
  layers:
    - type: conv2d
      filters: 32
      kernel_size: 3
    
    - type: relu
      
    - type: max_pool2d
      kernel_size: 2
    
    - type: conv2d
      filters: 64
      kernel_size: 3

    - type: relu

    - type: max_pool2d
      kernel_size: 2

    - type: flatten

    - type: linear
      units: 128
    
    - type: relu

    - type: linear
      units: 64
      
    - type: relu

    - type: linear
      units: 10
