experiment:
  name: adamw_mnist_base
  seed: 42
  output_dir: ./outputs/${experiment.name}
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.0001

includes:
  - ../models/simple_cnn.yaml
  - ../datasets/mnist_corrupted_flip_04.yaml



