experiment:
  seed: 42
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adamw
    lr: 0.01
    weight_decay: 0.0001

includes:
  - ../models/resnet18.yaml
  - ../datasets/cifar_corrupted_flip_04.yaml



