experiment:
  name: adamw_mnist_flip
  seed: 42
  output_dir: ./outputs/${experiment.name}
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.0001

  correction:
    method: model
    params:
      interval: 3
      top_p: 0.01

includes:
  - ../models/simple_cnn.yaml
  - ../datasets/mnist_corrupted_flip_04.yaml



