experiment:
  seed: 42
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adversarial
    data_len: 50000
    batch_size: ${training.batch_size}
    lr: 0.001
    weight_decay: 0.0001
    pi_lr: 0.0001
    pi_decay: 0.1
    mode: extragrad

includes:
  - ../models/resnet18.yaml
  - ../datasets/cifar_corrupted_unif_08.yaml



