experiment:
  name: adversarial_mnist_base_faster_decay
  seed: 42
  output_dir: ./outputs/${experiment.name}
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adversarial
    data_len: 60000
    batch_size: ${training.batch_size}
    lr: 0.001
    weight_decay: 0.0001
    pi_lr: 0.0001
    pi_decay: 0.1
    mode: extragrad

includes:
  - ../models/simple_cnn.yaml
  - ../datasets/mnist_corrupted_flip_04.yaml



