experiment:
  name: adversarial_mnist_flip
  seed: 42
  output_dir: ./outputs/${experiment.name}
  wandb_log: false

training:
  batch_size: 64
  epochs: 48
  optimizer:
    type: adversarial
    data_len: 60000
    batch_size: ${training.batch_size}
    lr: 0.001
    weight_decay: 0.0001
    pi_lr: 0.0001
    pi_decay: 0.01
    mode: extragrad
  
  correction:
    method: model
    params:
      interval: 1
      top_p: 0.01

includes:
  - ../models/simple_cnn.yaml
  - ../datasets/mnist_corrupted_flip_04.yaml



