experiment:
  name: adamw_corrupted
  seed: 42
  output_dir: ./outputs/${experiment.name}
  wandb_log: false

training:
  batch_size: 64
  epochs: 12
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.0001

  correction:
    method: model
    params:
      interval: 3
      top_p: 0.02

includes:
  - models/simple_cnn.yaml
  - datasets/mnist_corrupted.yaml



