optimizer:
  type: adversarial
  data_len: 50000
  batch_size: ${training.batch_size}
  lr: 0.001
  weight_decay: 0.001
  pi_lr: 0.001
  pi_decay: 0.1
  mode: extragrad
  is_min_min: true
  use_adam: false
  use_momentum: true
  momentum: 0.9